name: Strainberry CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'images/**'
      - '**/LICENSE'
      - '**/README.md'

jobs:
  
  example:
    name: Test Example (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ "ubuntu-latest", "ubuntu-18.04", "ubuntu-16.04" ]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sberry
          environment-file: environment.yml
          auto-activate-base: false
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Environment
        run: printenv | sort
      - name: Strainberry - Test Example
        run: ../strainberry -r assembly.fasta -b alignment.sorted.bam -o sberry_out
        working-directory: ./example
      - name: Remove output directory
        run: rm -rf sberry_out
        working-directory: ./example
